### PR TITLE
Few changes to google scholar service

### PR DESCRIPTION
**Pull request by artlowel**
I made a few changes to the google scholar service: renamed it, removed some redundant imports

### CODE REVIEW

**Comment by wellingWilliam** [comment]
item.model.ts has a syntax error. Looks like a letter i was accidental typed.

**Comment by wellingWilliam** [comment]
I dont think this works: [routerdata]="item"

**Comment by wellingWilliam** [comment]
full-item-view.component.ts has a strange import:
import {ItemStoreService} from '../../utilities/item-store.service'
import {IItemStore} from '../../utilities/item-store.service'

**Comment by DylanMeeus** [comment]
@wellingWilliam 
Indeed, that [routerdata] did not work, it was something I was trying out. Same for the import I left in, removed it.

I'm still changing how this works though. I'd want to remove the if-checks in the constructors of simple/full-item view. And make the item-store support more DSO rather than just items.

**Comment by wellingWilliam** [comment]
I think passing data through a router from parent component to child component is a work in progress for Angular2.

**Comment by wellingWilliam** [comment]
Honestly, I prefer the Injection of the parent component as the current workaround until Angular2 supports passing data through the router. This is a lot of work and code that will eventually not be needed. Angular2 is still in beta.

**Comment by wellingWilliam** [comment]
If you and Art would rather use a service, I am fine with it. Let me know when this pull request is ready. Thanks.

**Comment by wellingWilliam** [comment]
Could we not just do this? 

https://github.com/wellingWilliam/angular2-ui-prototype/tree/item-dspace-store-breadcrumb-visit

**Comment by artlowel** [comment]
I said yesterday that I'd look into this further, but I didn't have the time today, so I asked Dylan to take over. I said to him that I'd like it if the full/simple templates worked with items directly, instead of through an intermediate object. 
If you feel this is over-elaborate, then simply close this pull-request, and I'll merge your version. 
But I think his solution has the advantage that everything that's part of the workaround is confined to the constructor of the component. So when the angular solution comes around, we won't have to make many modifications

**Comment by wellingWilliam** [comment]
I don't mean to rush or contend. I am not sure how Angular2 will end up implementing such features.

**Comment by DylanMeeus** [comment]
No worries, I don't think anyone knows that yet, we'll have to wait and see. :-)

Your approach in that branch is similar to my initial approach for this problem. The issue remains that in the item views you have 'store.item.*', rather than just having the UI binds deal with 'item'. 
If it truly is similar to what I tried, than binding to item directly will cause some issues on updating the property. 

So if we want to just use 'item' everywhere, we will have to work with Rx. We could take this approach inside the dspace.store rather than making an item.store. Given that in the future it might need to pass more than just items, it could actually be a better place to do this. But we would end up with the same workaround, just in a different location.

**Comment by wellingWilliam** [comment]
What would be wrong with working with the item from store.item? Isn't it just a pointer to an item. It maintains binding.

**Comment by artlowel** [comment]
It violates the [law of demeter](https://www.wikiwand.com/en/Law_of_Demeter), the template shouldn't need to know about the store to do what it needs to.

**Comment by wellingWilliam** [comment]
Good point. I just accidentally pushed to my master branches changes I meant on a separate branch. 

I have to revert a pushed commit.

**Pull request merged**
